language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t gulmert89/docker-react -f Dockerfile.dev .
script:
    # This script is deprecated.
    # - docker run gulmert89/docker-react npm run test -- --coverage
    - docker run -e CI=true gulmert89/docker-react npm run test